### PR TITLE
Sync mi st

### PR DESCRIPTION
**Pull request by littlelazyexperiment**
Hello Sorgelig,

I have updated the Core with the last changes coming from MiST.
All the changes are straight forward: this is also why I could do them.
The last ones related to the implementation of Symbiface II support for IDE are beyond my catch at the moment, so they are not included. If you could have a look, this would be great.
Anyway, I hope this helps you maintain the Amstrad Core a little bit.

Cheers and thank you for all the inspiring work!

### CODE REVIEW

**Comment by sorgelig** [comment]
Did you check all those tricky demos manipulating CRTC?

**Comment by littlelazyexperiment** [comment]
No, I did not. The CRTC implementation looked identical to me between MiST
and MiSTer.
I assumed that if these changes had been successfully tested with the MiST,
it wouldn’t hurt aligning the implementation back together.
If you want, I can generate a test build and let the community check if it
is working as intended before you consider the changes?

Alexey Melnikov ***@***.***> schrieb am So. 23. Juli 2023 um
20:32:

**Comment by sorgelig** [comment]
It's ok to update, but CRTC is very sensitive part of Amstrad. Long time ago when i was working hard on Amstrad core it was pretty hard to tune CRTC to please all those tricky demos. And if you miss something then it won't work while it looks like the same as on MiST. So it's better to check if nothing broken and you didn't miss something.

**Comment by littlelazyexperiment** [comment]
I understand completely. I have generated a test build and posted a request for testing on the discord channel in the computer core thread. Let see if anyone is interested :-)

**Comment by Breiztiger** [comment]
Tested some demo ok
Just i think alt-f11 no necessary

**Comment by wwark** [comment]
I have tested also demos all seems to work great with verifying some with YT video if existed !

**Pull request merged**
